auto_gen = '<!-- AUTOGENERATED -->'
tmp_scripts = 'tmp.scripts'

index_file = open('index.html', 'r').read().split(auto_gen)

new_index = open('index.html', 'w')
new_index.write(index_file[0] + auto_gen + '\n' + open(tmp_scripts).read() +  auto_gen + index_file[2])
new_index.close()
